version: "3.9"
services:
  circuit-breaker:
    container_name: circuit-breaker-poc
    build: ./circuit-breaker-poc
    ports:
      - "5000:5000"
  dumb-localhost:
    container_name: dumb-localhost
    build: ./dumb-localhost
    ports:
      - "5001:5001"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # links: 
    #   - web